-- Create a custom type for recipe categories to ensure data consistency.
CREATE TYPE "public"."recipe_type" AS ENUM (
    'Breakfast',
    'Lunch',
    'Dinner',
    'Evening Tea'
);

-- Create the main 'recipes' table to store recipe information.
-- This table includes the new 'recipeType' column.
CREATE TABLE "public"."recipes" (
    "recipeNumber" text NOT NULL,
    "recipeName" text NOT NULL,
    "recipeType" recipe_type,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT recipes_pkey PRIMARY KEY ("recipeNumber")
);

-- Create the 'recipe_ingredients' table to store the many-to-many relationship
-- between recipes and ingredients. This makes the ingredients list flexible and optional.
CREATE TABLE "public"."recipe_ingredients" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "recipeNumber" text NOT NULL,
    "ingredientId" text NOT NULL,
    "quantity" real NOT NULL,
    "unit" text NOT NULL,
    CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_ingredients_recipeNumber_fkey FOREIGN KEY ("recipeNumber") REFERENCES recipes("recipeNumber") ON DELETE CASCADE,
    CONSTRAINT recipe_ingredients_ingredientId_fkey FOREIGN KEY ("ingredientId") REFERENCES ingredients("itemNumber") ON DELETE CASCADE
);

-- Enable Row Level Security for both tables.
ALTER TABLE "public"."recipes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."recipe_ingredients" ENABLE ROW LEVEL SECURITY;
